#include <Wire.h>
#include <LiquidCrystal_I2C.h>

// LCD

LiquidCrystal_I2C lcd(0x27, 16, 2);

// PINOS

const int TEMP_PIN = A2;
const int UMIDADE_PIN = A1;
const int LDR_PIN = A0;

const int LED_VERDE = 9;
const int LED_AMARELO = 10;
const int LED_VERMELHO = 11;
const int BUZZER = 8;

// LIMITES

const float TEMP_MIN = 10.0;
const float TEMP_MAX = 15.0;

const int UMIDADE_MIN = 50;
const int UMIDADE_MAX = 70;

const int LUZ_OK = 300;
const int LUZ_ALERTA = 600;

// VARIAVEIS

double tempC = 0;
int umidade = 0;
int leituraLuz = 0;

// TEMPO

unsigned long tempoLeitura = 0;
unsigned long tempoLCD = 0;

const long intervaloLeitura = 500;
const long intervaloLCD = 2000;

int tela = 0;

void setup() {

  pinMode(LED_VERDE, OUTPUT);
  pinMode(LED_AMARELO, OUTPUT);
  pinMode(LED_VERMELHO, OUTPUT);
  pinMode(BUZZER, OUTPUT);

  Serial.begin(9600);

  lcd.init();
  lcd.backlight();

  lcd.setCursor(0,0);
  lcd.print("Vinheria");

  lcd.setCursor(0,1);
  lcd.print("Monitorando");

  delay(2000);

  lcd.clear();
}

void loop() {

  unsigned long tempoAtual = millis();

  // LEITURA DOS SENSORES

  if (tempoAtual - tempoLeitura >= intervaloLeitura) {

    tempoLeitura = tempoAtual;

    int somaTemp = 0;
    int somaUmidade = 0;
    int somaLuz = 0;

    for (int i = 0; i < 5; i++) {

      somaTemp += analogRead(TEMP_PIN);
      somaUmidade += analogRead(UMIDADE_PIN);
      somaLuz += analogRead(LDR_PIN);

      delay(10);
    }

    int leituraTemp = somaTemp / 5;
    int leituraUmidade = somaUmidade / 5;
    leituraLuz = somaLuz / 5;

    double voltage = (leituraTemp / 1023.0) * 5000;
    tempC = (voltage - 500) * 0.1;

    umidade = map(leituraUmidade, 0, 1023, 10, 90);

    // SERIAL

    Serial.print("Temperatura: ");
    Serial.print(tempC);
    Serial.println(" C");

    Serial.print("Umidade: ");
    Serial.print(umidade);
    Serial.println("%");

    Serial.print("Luminosidade: ");
    Serial.println(leituraLuz);

    Serial.println("----------------");
  }

  // RESET LEDS

  digitalWrite(LED_VERDE, LOW);
  digitalWrite(LED_AMARELO, LOW);
  digitalWrite(LED_VERMELHO, LOW);

  bool problema = false;

  // LUMINOSIDADE

  if (leituraLuz < LUZ_OK) {

    digitalWrite(LED_VERDE, HIGH);
  }

  else if (leituraLuz < LUZ_ALERTA) {

    digitalWrite(LED_AMARELO, HIGH);
  }

  else {

    digitalWrite(LED_VERMELHO, HIGH);

    problema = true;
  }

  // TEMPERATURA

  if (tempC < TEMP_MIN || tempC > TEMP_MAX) {

    digitalWrite(LED_AMARELO, HIGH);

    problema = true;
  }

  // UMIDADE

  if (umidade < UMIDADE_MIN || umidade > UMIDADE_MAX) {

    digitalWrite(LED_VERMELHO, HIGH);

    problema = true;
  }

  // BUZZER

  if (problema) {

    tone(BUZZER, 1000);
  }

  else {

    noTone(BUZZER);
  }

  // LCD

  if (tempoAtual - tempoLCD >= intervaloLCD) {

    tempoLCD = tempoAtual;

    lcd.clear();

    // TELA 1
    if (tela == 0) {

      if (leituraLuz < LUZ_OK) {

        lcd.setCursor(0,0);
        lcd.print("");

        lcd.setCursor(0,1);
        lcd.print("");
      }

      else if (leituraLuz < LUZ_ALERTA) {

        lcd.setCursor(0,0);
        lcd.print("Ambiente a");

        lcd.setCursor(0,1);
        lcd.print("meia luz");
      }

      else {

        lcd.setCursor(0,0);
        lcd.print("Ambiente muito");

        lcd.setCursor(0,1);
        lcd.print("claro");
      }

      tela = 1;
    }

    // TELA 2
    else if (tela == 1) {

      if (tempC >= TEMP_MIN && tempC <= TEMP_MAX) {

        lcd.setCursor(0,0);
        lcd.print("Temperatura OK");

        lcd.setCursor(0,1);
        lcd.print(tempC);
        lcd.print(" C");
      }

      else if (tempC > TEMP_MAX) {

        lcd.setCursor(0,0);
        lcd.print("Temp. Alta");

        lcd.setCursor(0,1);
        lcd.print(tempC);
        lcd.print(" C");
      }

      else {

        lcd.setCursor(0,0);
        lcd.print("Temp. Baixa");

        lcd.setCursor(0,1);
        lcd.print(tempC);
        lcd.print(" C");
      }

      tela = 2;
    }

    // TELA 3
    else {

      if (umidade >= UMIDADE_MIN &&
          umidade <= UMIDADE_MAX) {

        lcd.setCursor(0,0);
        lcd.print("Umidade OK");

        lcd.setCursor(0,1);
        lcd.print(umidade);
        lcd.print("%");
      }

      else if (umidade > UMIDADE_MAX) {

        lcd.setCursor(0,0);
        lcd.print("Umidade Alta");

        lcd.setCursor(0,1);
        lcd.print(umidade);
        lcd.print("%");
      }

      else {

        lcd.setCursor(0,0);
        lcd.print("Umidade Baixa");

        lcd.setCursor(0,1);
        lcd.print(umidade);
        lcd.print("%");
      }

      tela = 0;
    }
  }
}